name: a5dmny
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.1.1
  image_picker: ^0.8.6
  uuid: ^3.0.7
  fluttertoast: ^8.1.2
  card_swiper: ^2.0.3
  firebase_database: ^10.0.9
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  permission_handler: ^10.2.0
  barcode_widget: ^2.0.3
  marquee: ^2.2.3
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_barcode_scanner: ^2.0.0
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  place_picker:
    git:
      url: https://github.com/mo-ah-dawood/locationpicker.git
      ref: nullsafety

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

